### ISSUE TITLE
[BUG] iPhone 7 not writing tags 

### ISSUE THREAD

**Issue by heyemuhlee** [placiibo/placiibo-bugs#6] opened 2020-05-17 20:29 UTC
**Describe the bug**

WHEN I HIT WRITE TAG THE PROGRESS BAR FLICKERS AND I ONLH GET THE BLUECHECK MARK BUT NOTHING HAS BEEN WRITTEN TO THE CARD 

**To Reproduce**

HAVE TRIED WRITING WITH DIFFERENT CARDS AND DIFFERENT BIN FILES AND RECEIVE THE SAME ERROR. 

CLICK BIN FILE 
CLICK WRITE 
SEE PROGRESS BAR FOR A SECOND 
EVENTUALLY GET BLUE CHECK MARK 

**Expected behaviour**
A clear and concise description of what you expected to happen

EXPECTED TO SEE PROGRESS BAR FULLY FILL FOLLOWED BY BLUE CHECK 

**Actual behaviour**
What actually happened instead

PROGRESS BAR APPEARED AND DISAPPEARED AND RECIEVED CHECK MARK AFTER TRYING TO POSITION IT AGAIN 

**Reproducibility :** 
How consistent can you reproduce the issue?

EVERY TIME 

**iOS version**:
Version of iOS this bug occurred on (can be found in Settings.app > General)

13.4.1 

**iOS device**: 
For example iPhone XS, iPhone 7, etc.
**Jailbroken**: 

iPhone 7 not jail broken 

Whether or not your device is jailbroken
**placiibo version + build**: 

0.1.0 

Version of placiibo this bug occurred on (can be found at the top on the About screen and in Testflight). Build is the number between parenthesis. e.g. *Version 0.1.0 (10)* 

**Screenshots**
If possible, add screenshots to help explain your problem.

![73BD4DF5-AA23-480C-B60C-CE3580347B91](https://user-images.githubusercontent.com/65510510/82159358-9061dd00-985b-11ea-9f5a-889916b0531c.png)

**Screen recording**
If possible, add a screen recording to help explain your problem.You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Relevant files**
If applicable, add the bin files that you used while the bug occurred

**NFC Tag**
If applicable, please include a screenshot from the [TagInfo app by NXP](https://apps.apple.com/us/app/nfc-taginfo-by-nxp/id1246143596) of the NFC tag that was used when the bug occurred. 
NTAG 215 

**Additional context**

**Comment by placiibo** [comment] 2020-05-17 20:43
Duplicate of Issue #1

**Closed** 2020-05-17 20:44 UTC
Labels: bug, duplicate, wontfix
